import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'initial-infiltration/quickstart',
        'initial-infiltration/installation',
        'initial-infiltration/termux',
        'initial-infiltration/nix-setup',
        'initial-infiltration/updating',
        'initial-infiltration/learning-path',
      ],
    },
    {
      type: 'category',
      label: 'Using Sovereign',
      collapsed: true,
      items: [
        'mission-guide/cli',
        'mission-guide/configuration',
        'mission-guide/sessions',
        'mission-guide/profiles',
        'mission-guide/git-worktrees',
        'mission-guide/docker',
        'mission-guide/security',
        'mission-guide/checkpoints-and-rollback',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: true,
      items: [
        'mission-guide/features/overview',
        'mission-guide/features/tool-gateway',
        {
          type: 'category',
          label: 'Core',
          items: [
            'mission-guide/features/tools',
            'mission-guide/features/skills',
            'mission-guide/features/memory',
            'mission-guide/features/memory-providers',
            'mission-guide/features/context-files',
            'mission-guide/features/context-references',
            'mission-guide/features/personality',
            'mission-guide/features/skins',
            'mission-guide/features/plugins',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          items: [
            'mission-guide/features/cron',
            'mission-guide/features/delegation',
            'mission-guide/features/code-execution',
            'mission-guide/features/hooks',
            'mission-guide/features/batch-processing',
          ],
        },
        {
          type: 'category',
          label: 'Media & Web',
          items: [
            'mission-guide/features/voice-mode',
            'mission-guide/features/browser',
            'mission-guide/features/vision',
            'mission-guide/features/image-generation',
            'mission-guide/features/tts',
          ],
        },
        {
          type: 'category',
          label: 'Management',
          items: [
            'mission-guide/features/web-dashboard',
            'mission-guide/features/dashboard-plugins',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            'mission-guide/features/rl-training',
          ],
        },
        {
          type: 'category',
          label: 'Skills',
          items: [
            'mission-guide/skills/godmode',
            'mission-guide/skills/google-workspace',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Messaging Platforms',
      collapsed: true,
      items: [
        'mission-guide/messaging/index',
        'mission-guide/messaging/telegram',
        'mission-guide/messaging/discord',
        'mission-guide/messaging/slack',
        'mission-guide/messaging/whatsapp',
        'mission-guide/messaging/signal',
        'mission-guide/messaging/email',
        'mission-guide/messaging/sms',
        'mission-guide/messaging/homeassistant',
        'mission-guide/messaging/mattermost',
        'mission-guide/messaging/matrix',
        'mission-guide/messaging/dingtalk',
        'mission-guide/messaging/feishu',
        'mission-guide/messaging/wecom',
        'mission-guide/messaging/wecom-callback',
        'mission-guide/messaging/weixin',
        'mission-guide/messaging/bluebubbles',
        'mission-guide/messaging/qqbot',
        'mission-guide/messaging/open-webui',
        'mission-guide/messaging/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/index',
        'integrations/providers',
        'mission-guide/features/mcp',
        'mission-guide/features/acp',
        'mission-guide/features/api-server',
        'mission-guide/features/honcho',
        'mission-guide/features/provider-routing',
        'mission-guide/features/fallback-providers',
        'mission-guide/features/credential-pools',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Tutorials',
      collapsed: true,
      items: [
        'guides/tips',
        'guides/local-llm-on-mac',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
        'guides/build-a-hermes-plugin',
        'guides/automate-with-cron',
        'guides/automation-templates',
        'guides/cron-troubleshooting',
        'guides/work-with-skills',
        'guides/delegation-patterns',
        'guides/migrate-from-openclaw',
        'guides/aws-bedrock',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: true,
      items: [
        'developer-guide/contributing',
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'developer-guide/architecture',
            'developer-guide/agent-loop',
            'developer-guide/prompt-assembly',
            'developer-guide/context-compression-and-caching',
            'developer-guide/gateway-internals',
            'developer-guide/session-storage',
            'developer-guide/provider-runtime',
          ],
        },
        {
          type: 'category',
          label: 'Extending',
          items: [
            'developer-guide/adding-tools',
            'developer-guide/adding-providers',
            'developer-guide/adding-platform-adapters',
            'developer-guide/memory-provider-plugin',
            'developer-guide/context-engine-plugin',
            'developer-guide/creating-skills',
            'developer-guide/extending-the-cli',
          ],
        },
        {
          type: 'category',
          label: 'Internals',
          items: [
            'developer-guide/tools-runtime',
            'developer-guide/acp-internals',
            'developer-guide/cron-internals',
            'developer-guide/environments',
            'developer-guide/trajectory-format',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/cli-commands',
        'reference/slash-commands',
        'reference/profile-commands',
        'reference/environment-variables',
        'reference/tools-reference',
        'reference/toolsets-reference',
        'reference/mcp-config-reference',
        'reference/skills-catalog',
        'reference/optional-skills-catalog',
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
